### ISSUE TITLE
Issue with more than 30 drones

### ISSUE THREAD

**Issue by andreabac3** [Andrea94c/DroNETworkSimulator#5]
Hi @Andrea94c, thank you for your works, I want point out one issue.

Branch hmw2: 
To reproduce that simply set the variable N_DRONES = 50 in config.py file, the error arise in the simulator so even if it's tested with RND or GEO algorithm.

Kind Regards,
Andrea

**Comment by Andrea94c** [comment]
Dear  @andreabac3,
Thank you for your feedback, you are right! On this branch/homework, you can only work with <= 30 drones. 

In fact, I've changed the mission (data/tours/RANDOM_mission_d30*) but I forgot to tell you that the new tours have only 30 drones. Therefore, for this homework just work with at most 30 drones (remember to have config.PATH_FROM_JSON = True.)

I also remember that: with other branches you can work with 90 drones (with config.PATH_FROM_JSON = True ) and without limits with (config.PATH_FROM_JSON = False).

I'll add a comment on the classroom, too.

Kind Regards,
Andrea Coletta
